### ISSUE TITLE
Change Request - Display Style

### ISSUE THREAD

**Issue by acidscorch** [DingoDjango/snStorageInfo#2]
Maybe changing the displayable variants to a more generic way? So, that the viewing seems mostly constant and the additional info if full or emtpy is only displayed as appendix. This would also only need two words to be translated: "full" and "empty", the rest could stay in code. 

ContainerEmpty: {$itemCount} / {$storageSpace} (empty)
ContainerNonEmpty: {$itemCount} / {$storageSpace}
ContainerFull: {$itemCount} / {$storageSpace} (full)

.json:
{
  "ContainerEmpty": "Leer",
  "ContainerFull": "Voll",
}

**Comment by DingoDjango** [comment]
Unfortunately this is not as easy as it would seem because of how Subnautica hadles inventory. I can tell how many total items there are, but to get the space they're occupying you actually need to do a lengthy calculation.

It's not done in a way to make this information readily available and easy to use. I would rather keep the mod as simple as possible right now.

**Comment by acidscorch** [comment]
I can build you the calculation, if you can tell me two things:
- can you provide which Items are stored in detail? (not only the Count)
- how much single slots the storage has?

**Comment by DingoDjango** [comment]
It's not about whether or not we can build a calculation. It would just be very expensive performance-wise. Getting the amount of single slots, on the other hand, is very easy.

I suggest you have a look at `ItemsContainer.cs` in Subnautica's code base to get a better idea of how much work is required.
